apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: "iot-gchopin"
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
subnet: "172.28.0.0/16"
ports:
  - port: 8080:443
    nodeFilters:
      - loadbalancer
  - port: 8888:8888
    nodeFilters:
      - loadbalancer