apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app1-volume
              mountPath: /usr/share/nginx/html/index.html
      volumes:
        - name: app1-volume
          hostPath:
            path: /vagrant/sites/app1.html
            type: File
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app2-volume
              mountPath: /usr/share/nginx/html/index.html
      volumes:
        - name: app2-volume
          hostPath:
            path: /vagrant/sites/app2.html
            type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: default
spec:
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app3-volume
              mountPath: /usr/share/nginx/html/index.html
      volumes:
        - name: app3-volume
          hostPath:
            path: /vagrant/sites/app3.html
            type: File