apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: argocd
spec:
  rules:
    - host: app1.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: development
                port:
                  number: 80