apiVersion: v1
kind: Service
metadata:
  name: development
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: development
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80