$server = <<-SCRIPT
curl -sfL https://get.k3s.io | \
 INSTALL_K3S_EXEC="server" \
 sh -s - --flannel-backend none --token 12345
SCRIPT

$client = <<-SCRIPT
curl -sfL https://get.k3s.io | \
 INSTALL_K3S_EXEC="agent --server https://k3s.example.com \
 --token mypassword" sh -s -
SCRIPT

Vagrant.require_version "2.4.5"
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_version = "20230607.0.5"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end

    config.vm.define "server" do |sv|
        sv.vm.hostname = "gchopinS"
        sv.vm.network "private_network", ip: "192.168.56.110"
        sv.vm.provision "shell", inline: $server
    end

    config.vm.define "sworker" do |swk|
        swk.vm.hostname = "gchopinSW"
        swk.vm.network "private_network", ip: "192.168.56.111"
        swk.vm.provision "shell", inline: $client
    end
end