Vagrant.require_version "2.4.5"
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
    end
    config.vm.define "server" do |sv|
    end
    config.vm.define "worker" do |wk|
    end
end